### ISSUE TITLE
ibm-dropdown not working when embedded inside another Angular component

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#104]
## Detailed description
I have created a new Angular component which contains an `ibm-dropdown`. When I display my component the dropdown doesn't behave correctly:

1. I see flashing when I try to select a dropdown item
2. I cannot select a dropdown item

> Is this a feature request (new component, new icon), a bug, or a general issue? Bug

> Is this issue related to a specific component? ibm-dropdown

> What browser are you working in? Chrome

> What version of the Carbon Design System are you using? 9.20.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Assess

## Steps to reproduce the issue
1. Clone this project https://github.com/markewallace/dropdown-app
2. Run `npm start`
3. Open the dropdown
4. Try to select an item

## Additional information
![ibm-dropdown](https://user-images.githubusercontent.com/3009737/45949908-7542b980-bff5-11e8-85fb-20e43c40243d.gif)

**Comment by cal-smith** [comment]
This one threw me for a loop for sure! Turns out Angulars change detection doesn't like it when you bind to a getter that always returns a new array [(context)](https://github.com/markewallace/dropdown-app/blob/master/src/app/sort/sort.component.ts#L20-L27) - the dropdown was infinitely re-initializing the list.

Since change detection in Angular is based on object identity, the easy fix is to keep the array in some extra variable and only change it when you want an update.

**Comment by cal-smith** [comment]
Going to close this to tidy the queue, feel free to re-open if there's something else 👍
