### ISSUE TITLE
Fix DAP issues for Dropdown

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-angular#112]
## Basic

Level | Description
-- | --
V | An element with WAI-ARIA role option is not contained in or owned by an element with one of the following WAI-ARIA roles: listbox. See rule help for remediation guidance. | Details
V | All content must reside within a WAI-ARIA landmark or labelled region role. | Details

## Multi-select

Level | Description
-- | --
V | Each form control must have associated label. | Details
V | An element with WAI-ARIA role option is not contained in or owned by an element with one of the following WAI-ARIA roles: listbox. See rule help for remediation guidance. | Details
V | All content must reside within a WAI-ARIA landmark or labelled region role. | Details
V | Widget with role of option must have no more than one tabbable element. | Details

**Comment by cal-smith** [comment]
### Basic
1. We have have to move the `role="listbox"` up in the tree
2. association or preview issue

### Multi-select
1. Technically correct, but assuming it's talking about the checkboxes, not valid since they aren't interactive. We could give them an `aria-label` with the `item.content` though
2. We have have to move the `role="listbox"` up in the tree
3. association or preview issue
4. I think this is just some `tabindex` mangement ... the checkboxes shouldn't be tabbable
