### ISSUE TITLE
Notification component support for links

### ISSUE THREAD

**Issue by kurtquackenbush** [IBM/carbon-components-angular#1240]
The Carbon Angular Notification component does not currently support the ability to make message content url links as described in the Carbon Design specification https://www.carbondesignsystem.com/components/notification/code.  All messages in z/OSMF (we use Notification Component to issue messages) require the ability to link to additional help content, which makes this linking capability critical to our project.

Thank you.

**Comment by cal-smith** [comment]
In the short term you should be able to use a template to display a link in the notification - https://github.com/IBM/carbon-components-angular/blob/master/src/notification/notification-content.interface.ts#L15

Thinking through the API, what would be most useful? Since the content is just a string, would it make sense to support a `links: string[]` option in the `NotificationContent`?

**Comment by Rolando77** [comment]
As requested by @cal-smith , the version Carbon-components-angular we are using is 2.49.10.  We are looking for linking capability (notification components) in this version.  Thank You.
