### ISSUE TITLE
ibm-combo-box doesn't support skeleton feature

### ISSUE THREAD

**Issue by juanbrusco** [IBM/carbon-components-angular#1283]
## Detailed description

> Possibility to add "skeleton" to ComboBox component

> Feature request

> ComboBox component

**Comment by zvonimirfras** [comment]
Doesn't seem to be supported by design at the moment and it's unclear to me what the purpose of this would be.
If a ComboBox doesn't have the data that goes into it, it would just display the default "Choose an option", or equivalent. It can also be additionally disabled until the options become available.

Considering this and that it's been a while since the issue was opened, if this is something you still feel like you need, open an issue in https://github.com/carbon-design-system/carbon and reopen this issue with a link to the newly created issue for tracking purposes. :)
