### ISSUE TITLE
Reduce lib size in node_modules

### ISSUE THREAD

**Issue by PaulaV22** [IBM/carbon-components-angular#1433]
## Detailed description

Is there a way to remove from node_modules all the components from carbon-components-angular that are not used in the project? carbon-components-angular is one of the largest folders in my project and my team would like to reduce its size. Other alternatives to use carbon without taking up so much space are welcome.

> What did you expect to happen? What happened instead? What would you like to see changed?

I would  like to keep in node_modules only the components that the project needs, cleaning all the unused components, or find another alternative to use carbon-components-angular library without saving all the possible components in node-modules.

> What version of the Carbon Design System are you using?

Using carbon-components-angular: 4.11.2 (78MB in node_modules)

**Comment by cal-smith** [comment]
Hey 👋 that's the goal of this PR https://github.com/IBM/carbon-components-angular/pull/1366 - definitely watch that space!

**Comment by cal-smith** [comment]
Hey 👋 Is this a bundle size issue? Or purely an on disk size issue? 

This PR - https://github.com/IBM/carbon-components-angular/pull/1366 - looks to fix the bundle size issues, but there's nothing we can do about installed on disk package size - it is what it is. Generally on disk size isn't an issue since Angular will optimize away any unused imports at compile time to reduce delivered bundle size!

**Comment by cal-smith** [comment]
I'm going to close this since there hasn't been any activity or responses in a while 👍 Don't hesitate to open new issues with further questions!
