### ISSUE TITLE
Need Multiple selection to be retained throughtout all the pages in ibm-table carbon-10

### ISSUE THREAD

**Issue by aaratichavan** [IBM/carbon-components-angular#1465]
Multiple selection (with checkbox) is working only on single page.
**Expected** -  If in first page, you select two rows then go to any other page in ibm- table then previous selected two rows should be displayed in Toolbar in all other pages too.

**Actual** - Selected rows from page are not getting displyed in Toolbar in other pages.

**Comment by zvonimirfras** [comment]
Hi @aaratichavan! Table model is designed to hold data about the currently displayed page. When you change the page, it loads the new data and the previous one is removed.
Since table does not (an cannot really) communicate with your backend to be aware of any changes that happen there, this is in the hands of the developer. Solving this in a generic way (that works for everybody) without imposing additional constraints is not practical.

In order to achieve what you're describing, you could maintain a separate "multi-page" table model to use in toolbar. You would need to keep `totalDataLength` accurate (above 0) and `rowsSelected` should have the correct number of rows selected.
Alternatively, you can use the "multi-page" table model as a cache of all the pages that user loaded (along with some identifier) and invalidate it based on backend data once it's available. You'd use that model for the table toolbar as well.
You can sync them using events available in the model you use for table.

I hope this helps.

**Comment by zvonimirfras** [comment]
A dup of #1109
