### ISSUE TITLE
Accessibilty: all <th> and <td> elements need to be related via 'header' or 'scope' attributes

### ISSUE THREAD

**Issue by ngalanmanlok** [IBM/carbon-components-angular#1569]
> Describe in detail the issue you're having.

The header elements created from TableHeaderItem do not have 'header' or 'scope' attributes defined. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Accessibility defect
 
> Is this issue related to a specific component?

ibm-table

> What did you expect to happen? What happened instead? What would you like to see changed?

The TableHeaderItem constructor should accept a parameter for defining 'headers' attribute

> What browser are you working in?

Chrome & Firefox

> What version of the Carbon Design System are you using?

    "carbon-components": "10.20.0"
    "carbon-components-angular": "4.17.0"

**Comment by cal-smith** [comment]
I believe this has been done ... each cell has a `headers` attribute with a list of related headers. Since we programmatically generate `id`s for the headers I'm not sure it's reasonable to expose a `headers` property as part of the `TableCell`. [See here for more on how we generate header `id`s](https://github.com/IBM/carbon-components-angular/blob/master/src/table/table-model.class.ts#L194-L226).

I'm going to close this since it appears to be addressed already. If you have a specific other need please open an issue for that (and consider contributing some code!).
