### ISSUE TITLE
Question only: Is AngularJS 1.8.x actual working with the carbon js lib?

### ISSUE THREAD

**Issue by sbodese** [IBM/carbon-components-angular#1612]
Hi Folks, im only interested on this question that AngularJs 1.8. is working fine with -and supports- the whole carbon design features ?

Thanks and Greetings

Steve

**Comment by theiliad** [comment]
Hi 👋 
AngularJS was started in 2009! Since 2.x it became known as just "Angular".

Angular 2 if I'm not mistaken was released in 2015 (5 years ago). Angular is on v11 now! https://blog.angular.io/version-11-of-angular-now-available-74721b7952f7

Considering that since 2.0 angular was almost fully re-written, I think it might not be ideal to expect a library that works with v11 to work with AngularJS. I'd recommend migrating your application if you have the bandwidth.

**Comment by cal-smith** [comment]
Yeah, I'll echo what @theiliad said - We don't have any plans to support AngjuarJS. Angular does provide a migration path, but if you're migrating an existing application to Carbon you may find it easier to approach this as a total rewrite since there's going to be a lot of styling changes as well.

I'm going to close this, but feel free to reach out with other questions (if you're an IBMer we have a #carbon-ng slack channel you can join).

**Comment by sbodese** [comment]
@cal-smith @theiliad Thanks!
