### ISSUE TITLE
File-Uploader emits fileChange on destroy

### ISSUE THREAD

**Issue by jerdaane** [IBM/carbon-components-angular#1632]
## Detailed description

I have a page with 'tabs'. one tab contains a file uploader, and another some other component. When I switch between these tabs, the `filesChange` is emitted. The end result is that in my data-model the selected file is removed, while the user did not do that.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug
> Is this issue related to a specific component?
file-uploader

> What did you expect to happen? What happened instead? What would you like to see changed?
I did not expect a `filesChange` when the component is destroyed

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
        "carbon-components": "10.24.0",
        "carbon-components-angular": "4.27.6",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

**Comment by Donisius** [comment]
@jerdaane If you set `cacheActive` to true on your `ibm-tabs` does it still emit `filesChange`? If you switch to another tab while `cacheActive` is false it would destroy all components in the preceding tab, and it seems like you want to keep the state of the tab contents.

**Comment by zvonimirfras** [comment]
Seems like `cacheActive` should solve the issue, feel free to reopen if the issue persists.

**Comment by mattia85** [comment]
Hello,
I'm having the same problem but I'm not using the tabs.
I'm using the file uploader inside an ibm modal, this is the file uploader configuration:
```
<ibm-file-uploader [accept]="acceptedFileExtensions"
    [multiple]="false"
    [(files)]="files"
    drop="true"
    dropText="Drag and drop files here or upload"
    (filesChange)="onDropped($event)">
</ibm-file-uploader>
```
The problem is that the **onDropped** method is called twice when selecting a second file (multiple=false).

Those are the steps to reproduce the issue:
1. select a file a confirm
2. without removing the first files, select a second file and confirm
3. the **filesChange** cb is called twice 

It seems that the issue starts calling clear method
https://github.com/IBM/carbon-components-angular/blob/c29d2a6126ac8d7f171bd6c4c87333327dfd871d/src/file-uploader/file-uploader.component.ts#L216

Let me know if you need more details.
