### ISSUE TITLE
Accordion inside an expanded accordion gets automatically expanded

### ISSUE THREAD

**Issue by Dani7B** [IBM/carbon-components-angular#166]
## Detailed description

I'm working on a **multi-level accordion**: an accordion might contains more accordions and so on.
Specifically, an <ibm-accordion> contains one or more <ibm-accordion-items> which in turn might contain more <ibm-accordion> | <ibm-accordion-item>.
_I would expect that when I expand the outermost accordion, the inner ones won't get expanded._ Instead, the graphical result is that all the accordions inside of an expanded accordion seems automatically expanded.

Furthermore, I noticed that when I set `<ibm-accordion-item expanded="false"></ibm-accordion-item>` the result is that the accordion-item is expanded! It should be the other way around, right?

As far as I can tell, _part of the problem might reside in the CSS_, since attributes are specified `.bx--accordion__item--active .bx--accordion__content`, affecting all the .bx--accordion__content elements descendant of .bx--accordion__item-active. The same thing applies to svg icons for the accordions.

I'm working in Safari 12 browser, btw.

I'm using Carbon components 1.8.3 for angular for a PoC. I might avoid using this component for a short time and replace it with an "handmade" one, so no special hurry.

## Additional information

I only clicked on the first accordion "Esempi" to expand the content. As you can see all the content inside looks expanded.
![schermata 2018-10-12 alle 19 05 35](https://user-images.githubusercontent.com/1493426/46883294-dec62300-ce51-11e8-815c-296c9f6691a9.png)

**Comment by zvonimirfras** [comment]
> Furthermore, I noticed that when I set <ibm-accordion-item expanded="false"></ibm-accordion-item> the result is that the accordion-item is expanded! It should be the other way around, right?

You're setting `expanded` to a string value of `"false"`, which is a truthy value. Do `[expanded]="false"` instead if you want to explicitly set it to false, otherwise, you don't have to set it to false, since that's the default value.

If you wish to statically expand it, both, `expanded="true"` and `[expanded]="true"` will do since one is a string and other is boolean, and they both resolve to truthy values.


From the rest of your message, what I'm understanding is that fixing css (for which you've already opened an issue 👍) will automagically fix the problem for all frameworks. I'll close this then, feel free to reopen if the issue persists after the css fix.

**Comment by Dani7B** [comment]
@zvonimirfras You are absolutely right about [expanded]="false". Thanks.
About the CSS issue, yeah, I'm suggesting the modification to the design team dealing with carbon components CSS. Let's see where it leads... ;-)

**Comment by seascherryy** [comment]
Is there any fix done for this issue?
