### ISSUE TITLE
[Feature Request] : Loading bar aswell as loading circle

### ISSUE THREAD

**Issue by CJMeek** [IBM/carbon-components-angular#1700]
## Brief Description

> It would be nice to have a loading bar in the same style as the loading circle

## Detailed description

> This is a feature request to include a loading bar as well as a loading circle.
> I find that the loading circle can be a bit intrusive whereas a bar can show proper loading progress.
> This came about when trying to show loading progress from an api to change data on a table, it would be nice to have a loading bar about the same length as the table just to show progress.

**Comment by cal-smith** [comment]
Since this a design language level request, please re-open this as an issue over on the Carbon repo - https://github.com/carbon-design-system/carbon

I would expect this to require designs and styles. Once those are settled and shipped in `carbon-components` we can look at adding a loading bar component.

In the interim you could try the small loading circle https://angular.carbondesignsystem.com/?path=/story/components-loading--basic (see the knobs tab, "Size of the loading circle" option)
