### ISSUE TITLE
Is there a documentation or example around usage of scrollLoad in ibm-table?

### ISSUE THREAD

**Issue by oprabhudesai** [IBM/carbon-components-angular#1710]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

**Comment by zvonimirfras** [comment]
Hi Omkar, there is [developer documentation](https://angular.carbondesignsystem.com/documentation/classes/src_table.table.html#scrollload).

It should be very straightforward: when user scrolls within `scrollLoadDistance` from the end of the table `scrollLoad` fires.
You can listen for the event and load more data into the `model`. It's up to the developer (obviously) to query the backend and update the model. Updating would go similar to the way it goes in paginated table with another (obvious) difference being developer would append the data in the model instead of replacing it.
