### ISSUE TITLE
Angular 11

### ISSUE THREAD

**Issue by rcaceiro** [IBM/carbon-components-angular#1712]
## Detailed description

First of all the @carbon/charts-angular, caron-components and carts-components-angular fail on instalation process because they aren't compatible with angular 11 I have to use the --force flag
And next after install everything it throws an error of "Missing CSS styles for Carbon Charts. Please read the Carbon Charts getting started guide."

> Is this a feature request (new component, new icon), a bug, or a general issue?

New feature/bug

> Is this issue related to a specific component?

Module in general

> What did you expect to happen? What happened instead? What would you like to see changed?

Show the chart correctly

> What browser are you working in?

Google Chrome 87

> What version of the Carbon Design System are you using?

@carbon/charts v0.41.27
carbon-components 10.26.0
carbon-components-angular 4.38.1
d3 v5.14.2

**Comment by cal-smith** [comment]
I'm not sure what you mean by "fail on instalation process because they aren't compatible with angular 11 I have to use the --force flag", I can `npm i` all of those packages just fine. None of those packages support Angular CLI schematics, so `ng add` won't work for them - this is something we'd like to address but don't have the bandwidth for at the moment.

As for your missing CSS, have you consulted the Carbon Charts getting starting guide as the error suggests?

From the information you've provided I don't see an issue with our Angular 11 support. Please open issues with specific errors if they arise, and be sure to check out https://github.com/carbon-design-system/carbon-charts/ for Carbon Charts specific issues/guidance.
