### ISSUE TITLE
[Compatibility] Is carbon-component-angular compatible with carbon-component 11

### ISSUE THREAD

**Issue by chayanray** [IBM/carbon-components-angular#2216]
## Detailed description
carbon-components-angular has peer dependency with carbon-component v10

In package.json 
"carbon-components": "^10.0.0"

Is the latest version compatible with carbon-components v11?

**Comment by Akshat55** [comment]
Hi @chayanray, currently we are testing Carbon v11. Let me know if you are interested in being our Sponsor User & trying out the migration process. 😃 


You can start consuming Carbon v11 by running `npm i carbon-components-angular@next`. You will need to use Angular v12 & greater. The migration documents can be found in the [wiki](https://github.com/IBM/carbon-components-angular/wiki/v4-to-v5-upgrade-guide).

You can also use this [storybook for reference](https://deploy-preview-2201--carbon-components-angular.netlify.app/?path=/story/getting-started--welcome) (URL subject to change on official release).

If you would like to see the code for v11, you can do so [here](https://github.com/IBM/carbon-components-angular/tree/next).

**Comment by chayanray** [comment]
Hi @Akshat55 
Thanks for the reply. There seems to be a few issues with Carbon 11 and angular at the moment.
First still not able to figure out how to import equivalent to the following in v11:

import { DataTable, Modal, Pagination } from 'carbon-components'; <-- v10 

Also sass loader in angular seems to be a big headache. Even '$spacing-02' or '$text-01' etc. which are indeed present in themes/colors are shown as undefined variables even with the proper modules being loaded. 

Any ideas on how to solve the above two issues?

**Comment by chayanray** [comment]
Hi @Akshat55
The angular library has peer dependency on Carbon v10, hence it would be difficult to let go of carbon-components v10 and upgrade to v11. Kindly advise.

**Comment by Akshat55** [comment]
carbon-components@v11 is carbon v11, it basically forwards the styles from `@carbon/styles` package.

Carbon v11 is not compatible with Carbon-components-angular (CCA) v4. 

Hence, CCA v4 will **_not_** get support for carbon v11 as it is a breaking change. The support for v11 is introduced in CCA v5, where `@carbon/styles` will be the new peer dependency. CCA v5 has additional breaking changes as we drop support for all Angular versions preceding Angular 12.

> You can start consuming Carbon v11 by running npm i carbon-components-angular@next. You will need to use Angular v12 & greater. The migration documents can be found in the [wiki](https://github.com/IBM/carbon-components-angular/wiki/v4-to-v5-upgrade-guide).
You can also use this [storybook for reference](https://deploy-preview-2201--carbon-components-angular.netlify.app/?path=/story/getting-started--welcome) (URL subject to change on official release).
If you would like to see the code for v11, you can do so [here](https://github.com/IBM/carbon-components-angular/tree/next).

We have NOT released a stable version of v5 as of yet, since we could not find any migration testers. So you if you're willing to try out the migration, that would be great and can bring us a step closer to an official release of CCA v5!

**Comment by chayanray** [comment]
@Akshat55  CCA v5 has peer dependency on carbon-components@v10 and hence will not allow installation of carbon-components@v11 at the same time. Kindly check the package.json and let me know if I am overlooking something.

**Comment by Akshat55** [comment]
@chayanray 

Root[ package.json](https://github.com/IBM/carbon-components-angular/blob/next/package.json) (carbon-components-angular@next) NOW has `@carbon/styles` as a peer dependency. Same goes for [package.json](https://github.com/IBM/carbon-components-angular/blob/next/src/package.json) in `src` directory.

**Comment by Akshat55** [comment]
Closing issue as it has been addressed in the responses. CCA@next supports Carbon 11, not via carbon-components package but `@carbon/styles`. Please reopen the issue or respond if you have any further questions regarding CCA & Carbon v11.
