### ISSUE TITLE
Vulnerabilities found with carbon-components-angular

### ISSUE THREAD

**Issue by spraju92** [IBM/carbon-components-angular#2221]
## Detailed description

Good day, Team. In one of my Angular projects, we're using the IBM carbon components, and everything is working as it should. However, as part our IBM company's policy i.e  ITSS chapter 5, we are required to run a static security scan on all of our projects using the 'HCL App Scan' tool. In this case, the 'App scan tool' discovered a few vulnerabilities in the respective Carbon components , which we were unable to fix. Because these are at the package level and we lack code controls for them. As a result, we need your help in addressing these vulnerabilities. For your convenience, I've attached vulnerability information. Thank you kindly.

## Package Versions

> carbon-components: "^10.52.0",
> carbon-components-angular: "^4.57.6"
 
[Carbon_components_vulnerabilities.docx](https://github.com/IBM/carbon-components-angular/files/9289811/Carbon_components_vulnerabilities.docx)

**Comment by Akshat55** [comment]
Will run a static scan & get back to you.

**Comment by Akshat55** [comment]
From the files attached, it appears as if you are running the static scan after building? 🤔 

I've run a `thorough` static scan via HCL App Scan, the vulnerabilities that were reported in your scan were not showing up for ours. Please update to the latest version of CCA & rerun the scan. Also, I would recommend you have a look at the code where date-picker & modal are being used/defined, we do not have any selectors called `carbon-modal` & `carbon-datepicker`.

Closing issue, since I cannot reproduce.
