### ISSUE TITLE
Toast: Shows `null` for title and caption in IE11

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#253]
## Detailed description

> Describe in detail the issue you're having.

Running the following code works fine in all browsers but IE11 shows additional content

```
    const bannerContent = {
      title: message.message,
      type: message.type === MessageType.Error ? "error" : "info",
      target: "#toast-root",
      duration: message.duration,
    };

    this.bannerService.showToast(bannerContent);
```

![image](https://user-images.githubusercontent.com/1253469/48151825-45433300-e290-11e8-894c-04b877c48c54.png)

- [ ] Fix `null` showing in the notification body
- [ ] Fix notification context doesn't wrap

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Toast

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

2.0.3 with 9.46.0 of carbon-components

**Comment by markewallace** [comment]
There are a couple of issues in the Toast documentation

1. 'type' does not support `danger`
1. Toast does not support `message`

**Comment by markewallace** [comment]
@cal-smith we have also run into this issue. Can this be fixed soon as we are planning our first public release in the next month.

**Comment by cal-smith** [comment]
Yep, let me look into it

**Comment by cal-smith** [comment]
Testing locally, I'm not seeing the `null` issue, so that appears to be resolved.

The line wrapping issue is a bit more complex, and something that should be dealt with in CSS ... either at the carbon-components level or your apps level. I don't want to hardcode something, because the `word-break` behavior is going to be different for each application.

for example:
default (correct if there are normal sized "words", but obviously broken here):
![image](https://user-images.githubusercontent.com/1744185/55740491-30163000-59f9-11e9-8e44-93f11fc82489.png)

`word-break: break-all;` (correct if you don't mind words wrapping in the middle, possible fix for Stan's issue):
![image](https://user-images.githubusercontent.com/1744185/55740537-4b813b00-59f9-11e9-9425-5f979bb82b45.png)

`word-break: break-word;` (correct if you're words aren't super long, _and_ you don't want them to break in the middle):
![image](https://user-images.githubusercontent.com/1744185/55740648-81262400-59f9-11e9-8ed9-6af624e248b6.png)

you can target `.bx--toast-notification__title` to apply the `word-break` style ... and it's supported in IE11 :+1:

**Comment by cal-smith** [comment]
I'll still make a PR for the docs issue
