### ISSUE TITLE
Table: Show a loading overlay on the entire tbody

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#316]
## Detailed description

> Describe in detail the issue you're having.

The loading indicator is showing after the data rows which can be below the fold giving the user a sense of "why is nothing happening?"

![image](https://user-images.githubusercontent.com/1253469/49893786-45e46180-fe1a-11e8-92d3-2d3fc631e695.png)

It would be great to use the Loading component as an overlay covering the entire table  `tbody` with it

![image](https://user-images.githubusercontent.com/1253469/49893906-93f96500-fe1a-11e8-96e6-95efdff03fee.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Table

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

2.4.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ADI

**Comment by cal-smith** [comment]
It would be ideal if you could add the loader as a sibling to the table and you could handle the loading states ... AFAIK the table model doesn't make any specific assumptions around data loading (if it does baking this in might be the pragmatic choice).

**Comment by stanislavgeorgiev** [comment]
I was just thinking about a small restyle with no other logic change. I'm fine with how the table model handles the loading state at the moment.
I'm working on a solution but I have some weird troubles the overlay positioning - I cannot make it to overlay only the `tbody` part for some reason

![image](https://user-images.githubusercontent.com/1253469/49947379-1a678280-febf-11e8-9b19-a351291f9c09.png)

What do you think about my assumption to cover the `tbody` and leave `thead` and `tfoot` uncovered?

**Comment by cal-smith** [comment]
Yeah I think restricting the spinner to the `tbody` makes a lot of sense ... Either that or cover the whole thing, but that doesn't seem ideal to me. I don't see the current style being very useful for paged tables, so this would definitely be an improvement.

Of course we'd want to keep the old style for endless scrolling tables ... though, I'm not sure carbon supports that? (CC @zvonimirfras cause you've looked at this more than I have).

I don't see any specific design guidance around loading table pages on the carbon website ... CC @aagonzales, since it'd be great if we could integrate any pre-exisiting patterns.

**Comment by zvonimirfras** [comment]
This is really old. Assuming that it's either no longer an issue or that you'll reopen if it still is :)

**Comment by stanislavgeorgiev** [comment]
Since then you introduced the skeleton states and we're using them instead of loader above :)
Good call to close it
