### ISSUE TITLE
[Question] Support for Carbon Grid layout

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#47]
## Detailed description
We are starting to use the Carbon Grid layout in our code and have been experimenting with create Angular components to abstract away the details.

Currently you would add markup like this to your template:

```html
<div class="bx--grid">
  <div class="bx--row">
    <div class="bx--offset-xs-2 bx--col-xs-10 bx--col-md-5">Some content here</div>
  </div>
</div>
```

This is rather verbose and difficult to write so we have created some components that reduces this to the following:

```html
<ibm-grid>
  <ibm-row>
    <ibm-column offset="{xs:2}" col="{xs:10, md:5}">Some content here</ibm-column>
  </ibm-row>
</ibm-grid>
```

For the case where no breakpoint needs to be specified could look like this:

```html
<ibm-grid>
  <ibm-row>
    <ibm-column offset="2" col="2">Some content here</ibm-column>
  </ibm-row>
</ibm-grid>
```

This would only work if we don't need to support break points and no break points at the same time. Not sure if this will always be the case.

So we wanted to get your feedback on this approach and your guidance on the best way to proceed.

**Comment by zvonimirfras** [comment]
I'm assuming verbosity and convenience is the only thing you're solving here.

You'd probably be better off with directives instead of components for these helpers. Components will likely need at least one additional html element and bloat your dom a bit.
You could even make it in a way that you can apply `offset` and `col` to regular html elements like `<div offset="2" col="2">Stuff</div>`, you may not need an `ibm-column`. It would be more convenient and fewer things to remember.

`offset` and `col` are just class builders, right?

If you pass in an object, it creates classes with breakpoints;
if it's a number, it creates ones for no breakpoints?

If you need both, you can just default to providing an object and have a special property for no breakpoints (`nobreak`?) and build all the classes.
In that case I'd consider writing `offset="2"` would be only a convenience around passing the full object like `[offset]="{nobreak: 2}"`

Does that make sense?

**Comment by markewallace** [comment]
@zvonimirfras thanks for the suggestions, we will try out that approach. If it works out we can open a PR to see if it's something worth adding to the library.

**Comment by cal-smith** [comment]
Yeah definitely think directives are an attractive way to go for this ... They give you a lot more control over the base presentation element (since the angular wrapper isn't technically a valid DOM element, it doesn't always get useful default styles).

**Comment by stanislavgeorgiev** [comment]
I think the `@HostBinding()` decorator is meant to do that just that - add attributes to the host element:

`<ibm-grid></ibm-grid>`

export class IbmGrid {
   @HostBinding('class')
   class = '--bx-grid';
}

Should result in:
`<ibm-grid class="--bx-grid"></ibm-grid>`

I haven't tested it but that's the general direction. The second part of that article talks about it:
https://www.infragistics.com/community/blogs/b/infragistics/posts/what-are-hostbinding-and-hostlistener-in-angular

**Comment by zvonimirfras** [comment]
That is accurate, Stan, we used it in multiple places.
Thing is, with components, you need _something_ in the template, so that something bloats the DOM if you don't need it. Directives don't have that limitation.
You can also apply directives to other tags so technically you could apply layouts to other components. You can't do that if layouts are done with components.
