### ISSUE TITLE
Update Dropdown.getDisplayValue documentation

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#472]
Question about this method https://github.com/IBM/carbon-components-angular/blob/master/src/dropdown/dropdown.component.ts#L341

The comment says _Returns the display value if there is no selection, otherwise the selection will be returned._

But the code does this
```
		} else if (selected) {
			return of(this.displayValue);
		}
```

I'm trying to find a way to control what displays as selected in three separate dropdowns at the dropdown level. They all display the same items so I cannot use the item `selected` property.

I thought I could use `displayValue` but it's not working as I expected.

**Comment by cal-smith** [comment]
Hmm, the comment is definitely out of date, a more correct one would be:

_Returns the display value if there is a selection and `displayValue` is set, if there is just a selection the `ListItem` content property will be returned, otherwise the `placeholder` will be returned._

something like:
```html
<ibm-dropdown
  displayValue="foo"
  placeholder="Select">
  <ibm-dropdown-list [items]="items"></ibm-dropdown-list>
</ibm-dropdown>
<ibm-dropdown
  displayValue="bar"
  placeholder="Select">
  <ibm-dropdown-list [items]="items"></ibm-dropdown-list>
</ibm-dropdown>
```

Works in the storybook (it should, each `dropdown-list` makes a copy of the items so state isn't shared) ... if you need additional context you can add any extra properties you want to the `ListItem`.

Maybe a minimal codesandbox would help clarify?

**Comment by markewallace** [comment]
Thanks @cal-smith no that makes sense. I thought the `displayValue` property worked in a different way. I can close this or leave it open if you want a reminder to update the comment?

**Comment by cal-smith** [comment]
We can leave this open for now :+1:

**Comment by cal-smith** [comment]
Fixed! Not sure with which PR, but it's done now 🎉
