### ISSUE TITLE
Overlay: cannot use overlay click (e.g. outside of modal) to close the modal

### ISSUE THREAD

**Issue by carmiele** [IBM/carbon-components-angular#505]
## Detailed description

> Describe in detail the issue you're having.

Clicking the modal overlay (outside of the modal) doesn't do anything, and doesn't close out of the modal as it's expected to.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Modal, specifically the Overlay component

> What did you expect to happen? What happened instead? What would you like to see changed?

Closing outside of the modal using the overlay should close the modal. Instead, there seems to be no event emitted to close.

> What browser are you working in?

Firefox 66, Chrome 73

> What version of the Carbon Design System are you using?
    
"carbon-components": "^9.79.2"
"carbon-components-angular": "^2.41.4"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM World Wire

## Steps to reproduce the issue

Currently exists in the current carbon-components-angular sandbox
1. Implement a button that opens/creates a modal via the ModalService
2. Click button to open modal
3. Proceed to click out of modal using the overlay
4. Watch nothing happen

## Additional information
N/A

**Comment by cal-smith** [comment]
Definitly an omission on our side ... If you're using `ModalService.create` with a custom modal component, you can listen to `overlaySelected` and call `closeModal`.

We need to:
- default to closing the modal when the overlay is clicked (so that `AlertModal`/`ModalService.show` have the correct defaults)
- give an escape hatch for applications that _don't_ want that (maybe overriding some method?)

This should probably go into v3 _and_ v2, since the behavior has been the same since carbon v9

**Comment by carmiele** [comment]
Yep! That's what I've been doing so far as a quick fix. Thanks for looking into it.

**Comment by cal-smith** [comment]
#511 sorts this out for v3 ... I think we're going to leave our defaults alone for fully custom modals - any other solution is going to be pretty clunky compared with `(overlaySelected)="closeModal()"`
