### ISSUE TITLE
Slider (v2): Initial `value` gets ignored

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#545]
## Detailed description

> Describe in detail the issue you're having.

Setting `value="30"` as an initial value gets ignored and shows the slider thumb at `0` instead.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Slider

> What version of the Carbon Design System are you using?

v2@latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/v2/?path=/story/slider--advanced
2. Go to Knobs
3. Set `value` to `30`

**Comment by stanislavgeorgiev** [comment]
Any chance of flowing this to v2 since it's a v2 issue?

**Comment by cal-smith** [comment]
Yep!

**Comment by nitishjain07** [comment]
I think there is some issue in the way slider component is initialising a slider value. If I give any initial value to slider in my component other than 0 it gives 'ExpressionChangedAfterItHasBeenCheckedError' error (PFA). I have also created quick demo to replicate this issue here - https://stackblitz.com/edit/carbon-slider-example.

![slider_error](https://user-images.githubusercontent.com/18714593/59246420-f4d2f000-8c39-11e9-9f11-5a27f2a3daf3.png)

**Comment by cal-smith** [comment]
Weird, we'll look into that too :+1: I think there's another issue open for that issue though

**Comment by cal-smith** [comment]
#582 and #584 supersede this ... closing again

**Comment by boeckMt** [comment]
Had the same Issue with `"carbon-components-angular": "^5.57.8"` when using the following example

```html

<cds-slider ...
        [value]="sliderValue"  (valueChange)="valueChange($event)">
        ...
</cds-slider>
```

```ts
valueChange(event){
   this.sliderValue = event;
}
```

Using `<cds-slider [(ngModel)]="sliderValue"></cds-slider>` helps to resolve this issue. Maybe a story with use of `ngModel` would be good for people which are new to `carbon-components-angular` :)
