### ISSUE TITLE
Why i18n and @ngx-translate in this library ?

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#63]
I'm wondering why UI component library at this level handling its own i18n texts and moreover dictating which i18n library to use ? Aren't i18n texts and which i18n library to use are completely for the top level application to provide and decide instead, and this library itself should stay agnostic ? 

References and comparisons : 
- https://github.com/angular-ui/bootstrap
- https://github.com/valor-software/ngx-bootstrap
 
Thank You

**Comment by zvonimirfras** [comment]
For translating instructional text in components and aria labels.

Do you have better approach we could use to translate those that would allow users to pick their own library?

**Comment by dsuwirya** [comment]
In my opinion, in order to stay agnostic, it's sufficient for UI library to provide default texts in EN, but then allow top level application which is using it to override / configure it ( if they wish ) via @Input parameters or even method ( if needed ) ? What do you think ?

FYI, this is our preferred i18n library : [angular-l10n](https://github.com/robisim74/angular-l10n) that we use in our application, and we prefer to use the directive approach over pipe / translate method - whenever we can in our view code.

**Comment by zvonimirfras** [comment]
It makes sense to be agnostic. It also makes sense to provide translatable strings in a way that they can be pulled into various internationalization libraries (like now in JSON) instead of having default input strings that are hard to pull out and translate, regardless of the translation library being used.

We have to explore our options before making changes for this one.

**Comment by dsuwirya** [comment]
Yes, I think externalizing strings to JSON [ K, V ] is still fine, as long as we can make this library not to hard-dictate / impose which translation library the app has to use ( but the bigger question here is probably: 'how?' ). 

Or I think it's still also acceptable if we can at least make this ngx-translate part somehow 'optional', in the sense that if ngx-translate is not present, don't fail the build - it's OK not to translate any text and just show the keys instead in this case.

I also think that we might want to give a more unique/specific namespace for the translation keys ( in en.json ) belong to this library, to avoid potential key collision with ones belong to the app ?

**Comment by cal-smith** [comment]
The decision on ngx-translate was made when it was the best answer to translations in angular ... And it was a good way for us to standardize on translations internally. However I think it is about time we rework our translation strategy, especially considering the growing number of options for i18n and translations in Angular. 

The biggest challenge I see, is in translating some of the "hidden" component labels ... It'd be awesome if apps didn't need to specify translations for everything ... But I don't see how we could do that while dropping our dependency on ngx-translate.

Ultimately it may be best if we either stopped providing translations, or we provided a lightweight way to manage our (few) needed internal translations. Maybe some service + pipes for internal use? With the provision that everything can be overridden.

Since we don't do a full i18n pass, but just a few translations, we may be able to get by with some small custom tool. Of course I'd also like to evaluate the possibility of directly including ngx-translate in that case as well.

**Comment by zvonimirfras** [comment]
If json files work across different translation libraries, we could still provide the same `en.json` (maybe others too?).
Then, to extend on Cal's idea, use dummy service/pipe to not really do anything but provide snippets in docs/readmes to extend their functionality and plug it in from other libraries.
We can provide exact code for the common ones and guidelines for DIY solutions.

The goal here is to get people to actually use globalization libraries (benefits the end user), just give them a choice.

**Comment by dsuwirya** [comment]
I like that, sounds like a good plan ! Thanks !

**Comment by cal-smith** [comment]
Possible plan of attack:

Components can provide `@Input()`s that default to the strings provided in `src/i18n/en.json` ... This keeps the project light (no extra dependencies) and easy for teams to configure/know what text to provide (thanks to the sample en.json).

Suggested `@Input` naming:

- `xLabel` -> `closeLabel`, `selectedLabel`
- `translations` self evident ... primarily for complex components like calendar with a lot of potential configurability

example:

```typescript
const EN = require("./../i1n/en.json");

// ... 

@Input() closeLabel = EN.BANNER.CLOSE_BUTTON;

//...
```

or

```typescript
const EN = require("./../i1n/en.json");

// ... 

@Input() translations = EN.CALENDAR;

//...
```
usage:

```html
<ibm-calendar [translation]="{ 'MONTHS': {}, 'SHORTWEEKDAYS': {} }"></ibm-calendar>
```

In this case the all caps style was chosen to make it obvious that these are weird constant values.

**Comment by dsuwirya** [comment]
I agree 100% with the lightweight @Input approach with default.
