### ISSUE TITLE
Form component(s)/helpers (?)

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-components-angular#70]
HTML and styles: http://www.carbondesignsystem.com/components/form/code
Usage: http://www.carbondesignsystem.com/components/form/usage

It's not clear to me what advantages can be added with this, apart from making a shell and providing styling to items. Thoughts?

**Comment by scarraway** [comment]
I think this would be a great addition actually - I can imagine a component with inputs like `label`, `placeholder`, `helperText`. And this component might support `formControlName` so that we can use the Angular form validation errors to display the Validation Text when they're applied to the form control.

**Comment by cal-smith** [comment]
I'm going to call this closed, since we have a nice assortment of form controls now. I'm pretty sure it covers all the carbon supported controls.
