### ISSUE TITLE
File Upload Component - file upload button doesn't have "type" attribute

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#734]
Add files button doesn't have "type" attribute. So it's submitting the form when using it inside the form which shouldn't happen.

I am using the below carbon version:
"carbon-components": "^10.5.1",
"carbon-components-angular": "^3.14.4"

**Comment by zvonimirfras** [comment]
@amirkhan064 looks like you've investigated the problem already and know what the fix is.
This looks like it might be a perfect contribution to open source opportunity for you, or is now a bad time? 😃 

[See our contributing guidelines](https://github.com/IBM/carbon-components-angular#contributing) and let us know 😉
