### ISSUE TITLE
move to monorepo

### ISSUE THREAD

**Issue by ninja511** [IBM/carbon-components-angular#818]

**Comment by cal-smith** [comment]
CC @joshblack We're planning on executing the move to the carbon monorepo in November ... We can use this issue to track any prep work we need to do or things we should be aware of so we can have a smooth transition.

**Comment by vpicone** [comment]
@cal-smith whats the motivation for moving into the monorepo?

**Comment by cal-smith** [comment]
@vpicone Hey Vince ... I'm sure most of the motivation should be self evident but:

- simplifies keeping pace with changes to `carbon-components` - ideally a structure or css change in `carbon-components` should be propagated to react/vue/angular in the same (or a related) PR
- centralizes issue logging for users - right now any cross implementation issue needs to be opened in several places
- should ensure library support in the event of a maintainer change - This is more of a hope, but given that carbon seems to be here for the long run the less places things are stored the better
- simplified contribution process (especially in the case of cross implementation changes)
- can take better advantage of shared tooling

I'm sure there's more that I'm missing, but that should cover the ones that immediately come to mind. On the whole it's a net benefit for the ecosystem, our contributors, and our users.

Let me know if you have any concerns 🙂 And don't worry - we won't need to special case the build process for _this_ project 😉

**Comment by vpicone** [comment]
@cal-smith thanks! Since none of the Carbon team members are experienced with Angular or familiar with this project some of those points don't exactly track for me. Since we won't be contributing to the Angular package, we won't exactly be able to take advantage of any of the 'keeping pace' or simplified contribution advantages. 

In regards to "should ensure library support in the event of a maintainer change," this is actually my primary concern. By bringing this package into the mono-repo it implies the Carbon team is at all responsible for the maintenance of this package (which we're definitely not prepared to take on).

**Comment by cal-smith** [comment]
> Since we won't be contributing to the Angular package, we won't exactly be able to take advantage of any of the 'keeping pace' or simplified contribution advantages.

I'm hoping we can change that. A framework shouldn't be the inhibiting factor for contribution. And while members of the Austin carbon team may choose to not contribute, the simplified contribution flow is absolutely relevant for all other contributions.

> By bringing this package into the mono-repo it implies the Carbon team is at all responsible for the maintenance of this package (which we're definitely not prepared to take on).

I feel like this deserves a huge `[citation needed]` ... To flip the issue around - what happens if my team disappears right now? Does Carbon stop supporting Angular? There are too many teams within IBM that rely on the maintenance of these components to continue taking that risk. At present we don't expect to be dissolving as a team any time soon, but by moving the project into the monorepo we can take advantage of all the infrastructure and policies around that.

I want to be crystal clear here - Angular **is** a first class citizen in the Carbon ecosystem. The sheer inertia behind us means that the Carbon organization as a whole **is** responsible for it's continued progress.

**Comment by vpicone** [comment]
I imagine the product teams using the library would rather pick it up than have it live in the monorepo of a team with no experience with Angular, let alone the library itself.

Perhaps moving the project to the carbon org would be a better way to associate it without the additional complexity/maintenance burden of integrating it into the monorepo?

**Comment by cal-smith** [comment]
I suppose the big question that's emerging here is: How do we support a multitude of frameworks, produced by a multitude of geographically diverse teams, shipping carbon in the least complex and maintenance heavy fashion possible?

Ideologically the monorepo solves a huge number of issues when it comes to the maintenance and collaboration burden of a design system such as carbon - however I've now heard from at least 2 other members that the monorepo simply adds complexity ... if we don't have the bandwidth to tackle the tooling required to make a monorepo an effective solution for cross team collaboration then I'm no longer sure it's a reasonable answer to the above question.

So how do we do it? Ultimately this is one part technical and one part social - On the technical front tooling such as the compliance test suit and perhaps some unified build utilities can help manage our growing universe of packages. On the social front some more deliberate efforts to communicate and cross contribute could help - pretending that we don't work on the same platform helps nobody, pretending that we can't contribute to other projects helps nobody. I don't believe for a second that framework choice is the limiting factor here - we're not the bad guys, we're just like the rest of you.

I realize this isn't a direct answer, but between this and the `icons-angular` issue this has clearly moved beyond it's original scope.

--------

Big side note here: For a long time the monorepo was positioned as _the_ solution to carbon packaging and contribution. The assumption was the tooling would fall in place and everyone would become part of a single repository - even all the addon packages. I was unaware that the stance on the monorepo had changed (hence this issue) - again, communication is key.

**Comment by vpicone** [comment]
@cal-smith if I gave the impression I was signaling a shift in Carbon’s official stance, that certainly wasn’t my intent. Just trying to get some more color around my concerns with this effort.

**Comment by cal-smith** [comment]
Perhaps in the future, considering being abundantly clear that you're looking to express your personal opinion.

Let me know if you have any concrete issues with this proposal, or feedback on how we can make the process easier.

**Comment by alisonjoseph** [comment]
Hey @cal-smith I'm going to schedule a meeting for us to discuss next week.

**Comment by cal-smith** [comment]
Sure :+1: I had some time blocked out with Vince and Josh next week, so we can use that time instead if you want?

**Comment by cal-smith** [comment]
After some further discussion we've tabled this for now ... we'll definitely investigate moving to the carbon-design-system org, but there's no clear appetite to commit to the level of work that the monorepo will require if we were to move in.
